import {
  GeneralLedgerAccount,
  GeneralLedgerAccountType,
} from "services/types/general.ledger.account.types";

export const GENERAL_LEDGER_ACCOUNTS_DATA: Array<GeneralLedgerAccount> = [
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "60000",
    description: "Inkopen artikelgroep 1",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "60001",
    description: "Inkopen schoenen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "60200",
    description: "Inkopen van diensten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "60300",
    description: "Uitbesteed werk",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "60400",
    description: "Inkopen van handelsgoederen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "60900",
    description: "Voorraadwijzigingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "60999",
    description: "Overige inkopen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "70000",
    description: "Mutatie voorraad gereed product",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "80000",
    description: "Omzet",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "80999",
    description: "Overige omzet",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "81000",
    description: "Verkoopkortingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "81500",
    description: "Doorbelaste kosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Revenue,
    code: "82000",
    description: "Huurinkomsten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40000",
    description: "Salarissen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40075",
    description: "Bijdrage spaarloon",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40100",
    description: "Premies en sociale lasten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40105",
    description: "Afdrachtsvermindering",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40110",
    description: "Ziekengeld verzekering",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40125",
    description: "Eindheffing loonheffing",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40130",
    description: "Storting eigen pensioenvoorziening",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40150",
    description: "Pensioenen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40200",
    description: "Reiskostenvergoedingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40300",
    description: "Opleidingskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40400",
    description: "Onkostenvergoedingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40450",
    description: "Overige vergoedingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40500",
    description: "Uitzendkrachten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40510",
    description: "Management fees",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40520",
    description: "Uitbesteed werk",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40600",
    description: "Kantine en consumptie",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40650",
    description: "Personeelsuitjes",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40700",
    description: "Kosten van werving en selectie",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40750",
    description: "Arbokosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40800",
    description: "Uitkeringen ziekengeld",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40900",
    description: "Werkkleding",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40950",
    description: "Vakantiegeld",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40960",
    description: "Vakantiedagen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40961",
    description: "Kort verzuim",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40962",
    description: "Feestdagen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40970",
    description: "WKR kosten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40980",
    description: "Overboekingsrekening personeelskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "40990",
    description: "Overige personeelskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41000",
    description: "Huur bedrijfspand",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41100",
    description: "Servicekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41200",
    description: "Gas, water & elektra",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41300",
    description: "Onderhoud pand",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41320",
    description: "Afval ophalen en verwerken",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41350",
    description: "Onderhoud inventaris",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41400",
    description: "Schoonmaakkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41500",
    description: "Verzekering pand",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41510",
    description: "Inboedelverzekering",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41600",
    description: "Lokale heffingen en belastingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41610",
    description: "Taxatiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41980",
    description: "Overboekingsrekening huisvestingskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "41990",
    description: "Overige huisvestingskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42000",
    description: "Leasekosten auto's",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42100",
    description: "Huurkosten auto's",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42200",
    description: "Brandstof",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42300",
    description: "Onderhoud auto's",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42400",
    description: "Verzekeringen auto's",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42500",
    description: "Kilometervergoedingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42600",
    description: "Wegenbelasting",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42610",
    description: "Kilometerheffingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42800",
    description: "Eigen bijdrage auto",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42900",
    description: "Verkeersboetes",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42950",
    description: "Parkeergelden",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42980",
    description: "Overboekingsrekening autokosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "42990",
    description: "Overige autokosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "43000",
    description: "Transportkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "43100",
    description: "Opslagkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "43980",
    description: "Overboekingsrekening distributiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "43990",
    description: "Overige distributiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44000",
    description: "Bureaukosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44050",
    description: "Marketing materialen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44060",
    description: "Marketing acties",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44070",
    description: "Relatiegeschenken",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44100",
    description: "Advertentiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44200",
    description: "Sponsoring",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44300",
    description: "Beurskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44400",
    description: "Representatiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44450",
    description: "Lunches en diners",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44500",
    description: "Reis- en verblijfskosten verkoop",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44700",
    description: "Provisies",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44800",
    description: "Incassokosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44850",
    description: "Afschrijvingskosten dubieuze debiteuren",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44900",
    description: "Giften en Donaties",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44980",
    description: "Overboekingsrekening verkoopkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "44990",
    description: "Overige verkoopkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45000",
    description: "Postverzendingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45100",
    description: "Telefoon- en internetkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45200",
    description: "Contributies en abonnementen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45250",
    description: "Vakliteratuur",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45300",
    description: "Kantoorartikelen en drukwerk",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45310",
    description: "Kleine aanschaffen kantoor",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45350",
    description: "Automatiseringskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45400",
    description: "Verzekeringen algemeen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45401",
    description: "Rechtsbijstandsverzekering",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45402",
    description: "Aansprakelijkheidsverzekering",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45500",
    description: "Administratie- en accountantskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45600",
    description: "Notaris- en advocaatkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45601",
    description: "Makelaar & taxatiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45610",
    description: "Overige adviseurs",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45620",
    description: "Consultants",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45650",
    description: "Beveiligingskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45670",
    description: "Reis- en verblijfkosten algemeen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45680",
    description: "Congressen en seminars",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45700",
    description: "Vergunningen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45750",
    description: "Boetes",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45760",
    description: "Incassokosten (boete)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45800",
    description: "Bankkosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45850",
    description: "Koersverschillen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45900",
    description: "Betalingsverschillen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45905",
    description: "Betalingskorting",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45910",
    description: "Btw-correcties",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45920",
    description: "Privé-gebruik kosten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45950",
    description: "Kasverschillen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45955",
    description: "Diverse contante uitgaven",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45980",
    description: "Overboekingsrekening algemene kosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "45990",
    description: "Overige algemene kosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "46000",
    description: "Productiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "46980",
    description: "Overboekingsrekening productiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "46990",
    description: "Overige productiekosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "47000",
    description: "Aanschaf kleine machines en gereedschap",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "47050",
    description: "Huur van machines en gereedschappen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "47100",
    description: "Onderhoud machines en installaties",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "47200",
    description: "Verlies en diefstal gereedschap",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "48000",
    description: "Afschrijvingskosten oprichtingskosten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "48100",
    description: "Afschrijvingskosten uitgifte van aandelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "48200",
    description: "Afschrijvingskosten onderzoek en ontwikkeling",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "48300",
    description:
      "Afschrijvingskosten concessies, vergunningen en intellectuele eigendom",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "48400",
    description: "Afschrijvingskosten goodwill",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "48500",
    description: "Afschrijvingskosten software licenties",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49000",
    description: "Afschrijvingskosten panden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49050",
    description: "Afschrijvingskosten verbouwingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49100",
    description: "Afschrijvingskosten machines en installaties",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49200",
    description: "Afschrijvingskosten inventaris en inrichting",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49300",
    description: "Afschrijvingskosten hardware",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49400",
    description: "Afschrijvingskosten software",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49500",
    description: "Afschrijvingskosten auto's",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49600",
    description:
      "Afschrijvingskosten niet aan de bedrijfsuitvoering dienstbare activa",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "49999",
    description: "Overboekingsrekening afschrijvingskosten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Costs,
    code: "88500",
    description: "Herwaardering voorraden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "45906",
    description: "Ontvangen betalingskorting",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "81010",
    description: "Kredietbeperking",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "85000",
    description: "Rente baten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "85400",
    description: "Rente op overige langlopende vorderingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "85800",
    description: "Rente op VPB",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "85990",
    description: "Diverse financiële baten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "86000",
    description: "Betaalde rente",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "86400",
    description: "Hypotheekrente",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "86600",
    description: "Betaalde rente op andere leningen en schulden",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "86700",
    description: "Rente op stamrechtverplichting",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "86710",
    description: "Storting lijfrente",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "86900",
    description: "Overige betaalde rente",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "86990",
    description: "Overige financiële lasten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "87500",
    description: "Boekverlies verkoop vaste activa",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "89000",
    description: "Buitengewone baten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "89050",
    description: "Subsidie",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.FinancialIncomeExpenses,
    code: "89100",
    description: "Buitengewone lasten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Taxes,
    code: "90000",
    description: "Vennootschapsbelasting",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Taxes,
    code: "99999",
    description: "Overboeking van het resultaat",
    deductible: 0,
  },

  {
    type: GeneralLedgerAccountType.Assets,
    code: "1000",
    description: "Oprichtingskosten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1050",
    description: "Afschrijving oprichtingskosten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1100",
    description: "Kosten van uitgifte van aandelen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1150",
    description: "Afschrijving kosten van uitgifte van aandelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1200",
    description: "Onderzoek en ontwikkeling",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1201",
    description: "Onderzoek en ontwikkeling (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1250",
    description: "Afschrijving onderzoek en ontwikkeling",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1300",
    description: "Concessies, vergunningen en intellectuele eigendom",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1301",
    description:
      "Concessies, vergunningen en intellectuele eigendom (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1350",
    description:
      "Afschrijving concessies, vergunningen en intellectuele eigendom",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1400",
    description: "Goodwill",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1401",
    description: "Goodwill (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1450",
    description: "Afschrijving goodwill",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1500",
    description: "Software en software licenties",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1501",
    description: "Software en software licenties (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1550",
    description: "Afschrijving software en software licenties",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "1900",
    description: "Vooruitbetaald op immateriële vaste activa",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2000",
    description: "Grond",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2001",
    description: "Grond (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2050",
    description: "Afschrijving terreinen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2100",
    description: "Panden",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2101",
    description: "Panden (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2110",
    description: "Verbouwingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2150",
    description: "Afschrijving panden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2160",
    description: "Afschrijving verbouwingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2180",
    description: "Onroerend goed (reserve)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2185",
    description: "Afschrijvingen gebouwen (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2200",
    description: "Machines en installaties",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2201",
    description: "Machines en installaties (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2250",
    description: "Afschrijving machines en installaties",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2280",
    description: "Machines en installaties (vrij)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2285",
    description: "Afschrijvingen machines en installaties (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2300",
    description: "Inventaris en inrichting",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2301",
    description: "Inventaris en inrichting (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2350",
    description: "Afschrijving inventaris en inrichting",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2380",
    description: "Inrichting (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2385",
    description: "Afschrijvingen inventaris (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2400",
    description: "Hardware",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2401",
    description: "Hardware (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2450",
    description: "Afschrijving hardware",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2480",
    description: "Kantoormachines (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2485",
    description: "Afschrijving van hardware (vrij)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2500",
    description: "Software",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2501",
    description: "Software (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2550",
    description: "Afschrijving software",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2600",
    description: "Vervoermiddelen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2601",
    description: "Auto's (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2650",
    description: "Afschrijving auto's en andere vervoermiddelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2680",
    description: "Overige vervoermiddelen (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2685",
    description: "Afschrijvingen overige vervoermiddelen (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2700",
    description: "Vaste activa in uitvoering",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2701",
    description: "Vaste activa in uitvoering (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2780",
    description: "Vaste activa in uitvoering (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2785",
    description: "Afschrijvingen VA in uitvoering (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2800",
    description: "Gebouwen en terreinen in lease",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2808",
    description: "Herwaardering gebouwen en terreinen in lease",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2809",
    description: "Afschrijving gebouwen en terreinen in lease",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2880",
    description: "Vaste activa in leasing (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2885",
    description: "Afschrijvingen VA in leasing (reserve)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2900",
    description: "Niet aan de bedrijfsuitvoering dienstbare activa",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2901",
    description: "Niet aan de bedrijfsuitvoering dienstbare activa (verkopen)",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2950",
    description:
      "Afschrijving niet aan de bedrijfsuitvoering dienstbare activa",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2980",
    description: "Andere vaste bedrijfsmiddelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2985",
    description: "Afschrijvingen overige vaste bedrijfsmiddelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2990",
    description: "Biologische Activa",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "2999",
    description: "Tussenrekening beginbalans activa",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3000",
    description: "Groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3001",
    description: "Groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3002",
    description: "Groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3003",
    description: "Groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3004",
    description: "Groepsmaatschappij Anna Pancakes Berlijnplein B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3005",
    description: "Groepsmaatschappij Anna Pancakes Lichtegaard B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3006",
    description: "Groepsmaatschappij Anna Pancakes Utrecht Centrum B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3100",
    description: "Lening aan groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3101",
    description:
      "Lening aan groepsmaatschappij Anna Pancakes Utrecht Centrum B.V.",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3102",
    description: "Lening aan groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3103",
    description:
      "Lening aan groepsmaatschappij Anna Pancakes Berlijnplein B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3104",
    description: "Lening aan groepsmaatschappij Anna Pancakes Lichtegaard B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3105",
    description:
      "Lening aan groepsmaatschappij Anna Pancakes Utrecht Centrum B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3200",
    description: "Deelneming Anna Pancakes Lichtegaard B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3201",
    description: "Deelneming Anna Pancakes Utrecht Centrum B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3202",
    description: "Deelneming Anna Pancakes Berlijnplein B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3300",
    description: "Lening aan deelneming {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3301",
    description: "Lening aan deelneming {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3400",
    description: "Overige langlopende vorderingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3500",
    description: "Overige langlopende effecten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3550",
    description: "Waarborgsommen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3600",
    description: "Lening aan Anna Pancakes Holding B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "3800",
    description: "Lening u/g (vrij)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "8990",
    description: "Aandeel derden in groepsvermogen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "10000",
    description: "Anna Pancakes Utrecht Centrum B.V. Kas",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "10001",
    description: "Anna Pancakes Lichtegaard B.V. Kas",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "10002",
    description: "Anna Pancakes Berlijnplein B.V. Kas",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "10003",
    description: "Anna Pancakes Vredenburg B.V. Kas",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "11000",
    description: "Betaalrekening Utrecht Centrum 525",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "11001",
    description: "Betaalrekening holding 266",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "11002",
    description: "Betaalrekening Lichtegaard 674",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "11003",
    description: "Betaalrekening AP Berlijnplein *885",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "11004",
    description: "NL20 ABNA 0130 3720 80",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "11099",
    description: "Tussenrekening beginbalans banken",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "12000",
    description: "Spaarrekening holding 912",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "12001",
    description: "Bankgarantie Dekkingsrekening 721",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "12500",
    description: "(Reserved for deposit account)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "12501",
    description: "Bankgarantie UC Utrecht Centrum B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13000",
    description: "Debiteuren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13001",
    description: "Tussenrekening beginbalans debiteuren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13010",
    description: "Overige handelsvorderingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13050",
    description: "Vorderingen > 1 jaar",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13100",
    description: "Dubieuze debiteuren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13200",
    description: "Nog te factureren",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13210",
    description: "Te ontvangen creditnota's",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13300",
    description: "Nog te ontvangen goederen en diensten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13350",
    description: "Vooruitbetalingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13400",
    description: "Kortlopende vorderingen op groepsmaatschappijen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13410",
    description: "Kortlopende vorderingen op overige deelnemingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13420",
    description: "Kortlopende vorderingen op participanten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13450",
    description: "Nog te ontvangen subsidie",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13460",
    description: "Waarborgsommen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13500",
    description: "Opgevraagde stortingen van aandeelhouders",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13600",
    description: "Nog te ontvangen interest",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13690",
    description: "Overige overlopende activa",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "13999",
    description: "Overige kortlopende vorderingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "14000",
    description: "Eigen aandelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "14050",
    description: "Overige aandelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "14100",
    description: "Obligatieleningen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "14999",
    description: "Overige effecten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "17900",
    description: "Tussenrekening VPB",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "18900",
    description: "Lokale btw in andere EU landen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23000",
    description: "Betalingen onderweg",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23010",
    description: "Rekening onbekend",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23020",
    description: "Vraagposten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23100",
    description: "Tussenrekening",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23101",
    description: "Vrije tussenrekening 1",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23102",
    description: "Tussenrekening Qredits",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23103",
    description: "tussenrekening fooi",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23104",
    description: "tussenrekening betalingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23105",
    description: "Tussenrekening Giftcard",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23106",
    description: "Tussenrekening op rekening",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23107",
    description: "Tussenrekening Viva Wallet",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23108",
    description: "Vrije tussenrekening 2",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23150",
    description: "Tussenrekening Beginbalans",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23200",
    description: "Tussenrekening kas",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23300",
    description: "Tussenrekening pinbetalingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23310",
    description: "Tussenrekening creditcard betalingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23320",
    description: "Tussenrekening iDEAL betalingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23330",
    description: "Tussenrekening online betalingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "23340",
    description: "Aangepaste tussenrekening",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "30000",
    description: "Voorraad grond- en hulpstoffen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "30100",
    description: "Onderhanden werk",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "30200",
    description: "Voorraad gereed product",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "30300",
    description: "Voorraad handelsgoederen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Assets,
    code: "30900",
    description: "Vooruitbetaald op voorraden",
    deductible: 0,
  },

  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5000",
    description: "Kapitaal {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5100",
    description: "Privéopnamen {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5200",
    description: "Privéstortingen {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5300",
    description: "Privébelastingen {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5400",
    description: "Privéverzekeringen {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5500",
    description: "Privé ziektekosten {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5600",
    description: "Fiscale oudedagsreserve",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5700",
    description: "Privé kosten (btw 75% aftrekbaar)",
    deductible: 75,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5701",
    description: "Prive autokosten (niet aftrekbaar)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "5900",
    description: "Overige privémutaties {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6000",
    description: "Voorziening groot onderhoud A",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6010",
    description: "Groot onderhoud panden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6100",
    description: "Voorziening dubieuze debiteuren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6200",
    description: "Voorziening pensioenen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6210",
    description: "Stamrechtverplichting",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6220",
    description: "Voorziening lijfrente",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6300",
    description: "Voorziening latente belastingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6400",
    description: "Voorziening assurantie eigen risico",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "6999",
    description: "Overige voorzieningen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7000",
    description: "Converteerbare leningen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7010",
    description: "Obligatieleningen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7020",
    description: "Onderhandse leningen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7100",
    description: "Hypotheek",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7110",
    description: "Overige leningen van kredietinstellingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7111",
    description: "Bridgefund",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7112",
    description: "Lening Rabobank",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7120",
    description: "Overige achtergestelde leningen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7200",
    description: "Achtergestelde lening van Anna Pancakes Holding B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7201",
    description: "Achtergestelde lening van Remco de Medeiros Carneiro",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7300",
    description: "Achtergestelde lening van deelneming {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7301",
    description: "Achtergestelde lening van deelneming {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7400",
    description: "Achtergestelde lening van groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7401",
    description: "Achtergestelde lening van groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7402",
    description: "Achtergestelde lening van groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7403",
    description: "Achtergestelde lening van groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7404",
    description:
      "Achtergestelde lening van groepsmaatschappij Anna Pancakes Berlijnplein B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7405",
    description:
      "Achtergestelde lening van groepsmaatschappij Anna Pancakes Lichtegaard B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7406",
    description:
      "Achtergestelde lening van groepsmaatschappij Anna Pancakes Utrecht Centrum B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7500",
    description: "Lening van Anna Pancakes Holding B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7600",
    description: "Lening van deelneming {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7700",
    description: "Lening van groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7701",
    description: "Lening van groepsmaatschappij Anna Pancakes Holding B.V.",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7702",
    description: "Lening van groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7703",
    description: "Lening van groepsmaatschappij {0}",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7704",
    description:
      "Lening van groepsmaatschappij Anna Pancakes Berlijnplein B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7705",
    description: "Lening van groepsmaatschappij Anna Pancakes Lichtegaard B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7706",
    description:
      "Lening van groepsmaatschappij Anna Pancakes Utrecht Centrum B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7800",
    description: "Lening o/g (vrij)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7900",
    description: "Langlopende leaseverplichtingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7901",
    description: "Terug te betalen NOW",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7910",
    description: "Langlopende leveranciers- en handelskredieten",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7920",
    description: "Langlopende belastingschulden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7930",
    description: "Langlopende pensioenschulden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7940",
    description: "Langlopende wissels en cheques",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7950",
    description: "Langlopende vooruitontvangen bestellingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7960",
    description: "Langlopende overlopende passiva",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "7999",
    description: "Overige langlopende schulden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8000",
    description: "Aandelenkapitaal",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8050",
    description: "Agioreserve",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8100",
    description: "Wettelijke reserve oprichtingskosten en uitgifte aandelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8110",
    description: "Wettelijke reserve deelnemingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8120",
    description: "Wettelijke reserve lening uitgifte aandelen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8130",
    description: "Wettelijke reserve minimumkapitaal",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8140",
    description: "Wettelijke reserve inbreng in natura",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8190",
    description: "Overige wettelijke reserves",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8200",
    description: "Statutaire reserves",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8210",
    description: "Continuïteitsreserve",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8220",
    description: "Bestemmingsreserve",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8300",
    description: "Ongerealiseerde herwaarderingsreserve",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8310",
    description: "Gerealiseerde herwaarderingsreserve",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8350",
    description: "Fiscale herinvesteringsreserve",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8400",
    description: "Algemene reserve",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "8900",
    description: "Overige reserves",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "9000",
    description: "Onverdeeld resultaat voorgaande boekjaren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "9999",
    description: "Resultaat lopend boekjaar",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "15000",
    description: "(Reserved for credit card)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16000",
    description: "Crediteuren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16001",
    description: "Tussenrekening beginbalans crediteuren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16100",
    description: "Nog te ontvangen facturen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16110",
    description: "Nog te crediteren",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16150",
    description: "Nog te leveren goederen en diensten",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16200",
    description: "Kortlopende deel converteerbare leningen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16210",
    description: "Kortlopende deel obligatieleningen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16220",
    description: "Kortlopende deel onderhandse leningen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16230",
    description: "Kortlopende deel hypotheek",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16240",
    description: "Kortlopende deel overige leningen kredietinstellingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16300",
    description: "Kortlopende schulden aan aandeelhouders",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16310",
    description: "Kortlopende schulden aan deelnemingen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16320",
    description: "Kortlopende schulden aan groepsmaatschappijen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16400",
    description: "Kortlopende leaseverplichtingen",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16500",
    description: "Te betalen dividend",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16510",
    description: "Te betalen dividendbelasting",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16520",
    description: "Te betalen tantièmes",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16530",
    description: "Te betalen interest",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16540",
    description: "Te betalen wissels en cheques",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16980",
    description: "Overige overlopende passiva",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16981",
    description: "Terug te betalen NOW kortlopend deel",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16982",
    description: "Terug te betalen TVL",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16983",
    description: "Uitstel belastingschulden Kortlopend deel",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "16999",
    description: "Overige kortlopende schulden",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17000",
    description: "Te betalen netto lonen en salarissen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17010",
    description: "Te betalen pensioenen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17100",
    description: "Loonheffing",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17105",
    description: "Ingehouden loonheffing",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17110",
    description: "Belastingschulden LB",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17200",
    description: "Te betalen pensioenpremies",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17300",
    description: "Afdracht premies en sociale lasten werkn. deel",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17310",
    description: "Afdracht premies en sociale lasten werkg. deel",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17500",
    description: "Reservering voor vakantiegeld",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17501",
    description: "Reservering voor vakantiedagen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17502",
    description: "Reservering kort verzuim",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17503",
    description: "Reservering feestdagen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17504",
    description: "Individueel keuzebudget",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17505",
    description: "Overige reserveringen",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "17600",
    description: "Af te dragen PAWW",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18000",
    description: "Btw over leveringen/diensten belast met hoog tarief",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18100",
    description: "Btw over leveringen/diensten belast met laag tarief",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18200",
    description:
      "Btw over leveringen/diensten belast met overige tarieven behalve 0%",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18300",
    description: "Btw inzake privé gebruik",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18400",
    description:
      "Btw over leveringen/diensten belast met 0% of niet bij jou belast",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18500",
    description: "Leveringen/diensten waarbij de heffing naar jou is verlegd",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18600",
    description: "Leveringen naar landen buiten de EU (uitvoer)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18610",
    description: "Leveringen naar landen binnen de EU",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18611",
    description: "Leveringen naar/diensten in landen binnen de EU",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18620",
    description: "Installatie/afstandsverkopen binnen de EU",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18625",
    description: "Digitale diensten binnen de EU (OSS)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18700",
    description: "Leveringen uit landen buiten de EU (invoer)",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18750",
    description: "Verwervingen uit landen binnen de EU",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18800",
    description: "Btw voorbelasting",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18850",
    description: "Vermindering volgens de kleineondernemersregeling",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18950",
    description: "Vrijgesteld van btw",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18990",
    description: "Overboekingsrekening btw-aangiften",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18991",
    description: "Btw fiscale eenheid",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "18999",
    description: "Te corrigeren btw",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20000",
    description: "RC personeel",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20010",
    description: "RC personeelsvereniging",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20100",
    description: "RC administraties",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20200",
    description: "RC Remco de Medeiros Carneiro",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20201",
    description: "RC Anna Pancakes Lichtegaard B.V.",
    deductible: 100,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20202",
    description: "RC Anna Pancakes Utrecht Centrum B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20203",
    description: "RC Anna Pancakes Holding B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20204",
    description: "RC Anna Pancakes Berlijnplein B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20205",
    description: "RC Anna Pancakes Vredenburg B.V.",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "20300",
    description: "RC vrij",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "24000",
    description: "Belastingschulden btw",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "24010",
    description: "Belastingschulden VPB",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "24020",
    description: "Overige binnenlandse belastingschulden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "24030",
    description: "Buitenlandse belastingschulden",
    deductible: 0,
  },
  {
    type: GeneralLedgerAccountType.Liabilities,
    code: "24040",
    description: "Betalingsuitstel Belastingschulden",
    deductible: 0,
  },
];
